[project]
name = "aws-lambda-durable-function-try"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aws-durable-execution-sdk-python>=1.0.0.post1",
    "requests>=2.32.5",
]
